### ISSUE TITLE
Foreign Constraint

### ISSUE THREAD

**Issue by marksburgess** [surveyproject/sp_main_public#10]
When I run the publish function from Visual Studio and drop everything in the database, recreate it and try to load data in a script generated by the database, I get this error.  The script is set to check constraints and check for object existence.  Why would there be a missing constraint?

Severity    Code    Description Project File    Line
Error       Web deployment task failed. (An error occurred during execution of the database script. The error occurred between the following lines of the script: "1504" and "1508". The verbose log might have more information about the error. The command started with the following:
"/*****\* Object:  Index [PK_vts_tbSurvey]    Script"
 The constraint 'PK_vts_tbSurvey' is being referenced by table 'vts_tbSurveyAsset', foreign key constraint 'FK__vts_tbSur__Surve__1387E197'.
Could not drop constraint. See previous errors. http://go.microsoft.com/fwlink/?LinkId=178587  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_SQL_EXECUTION_FAILURE.)   SurveyWAP       0

**Comment by fwsmaster** [comment]
Hello,

This seems more like a Visual Studio or Mssqlserver issue instead of an SP issue even though the constrains set in SP may at first sight seem to cause this. The solution must be found in the Webdeployment working of VS and Sqlserver.

Kind regards
SP coordinator
