### ISSUE TITLE
Inconsistent values with Field - Slider on save progress

### ISSUE THREAD

**Issue by jonpikum** [surveyproject/sp_main_public#11]
With an answer of type Field-Slider, saving your progress on the survey loads the wrong value after the process is complete...

Steps to reproduce: 
On a form with save progress mode set to manual
A slider with min value 1 and max value 10...
Open the survey and set the slider to 6, then click save progress
You will see the slider get set to 1 after progress has been saved.
If you click save progress a second time, after the process is complete, the slider will display 6 again
Clicking the save progress button a third time will change the slider to display 1 again.
Clicking save progress a fourth time will change the slider to 6 again

This seems to toggle back and forth indefinitely.

If you look at the HTML, you can clearly see that the input element's value is set to 6 when the slider displays 1, and the input element's value is set to 1 when the slider displays 6

**Comment by fwsmaster** [comment]
Hello,

The working of the Save Progress button is correct. After clicking the button Saving Progress a Resume Code is shown and the in between results have been saved to the database.

To restart the survey at later moment the Resume Progress button can be clicked. Next enter the Resume Code. The survey will now restart/ reopen at the last question that was answered. In the example the slider would be set at 6.

Clicking the Save Progress button repeatedly only creates new Resume codes over and over again.

Kind regards
SP coordinator
