### ISSUE TITLE
ResultsReport.aspx and CustomResult.aspx does not show anything

### ISSUE THREAD

**Issue by trup40** [surveyproject/sp_main_public#114]
# 1. ISSUE/ BUG/ ERROR  
## a. Expected Behaviour
NSurveyReports\CustomReport.aspx?surveyid=abcdefg should shows the results
NSurveyReports\ResultsReportaspx?surveyid=abcdefg should shows the results
  
## b. Actual Behaviour
"CustomResult.aspx?surveyid=something" shows the results if only I logged in, otherwise ti shows default login page.

"ResultsReport.aspx?surveyid=something" shows the results if only I logged in, otherwise ti shows default login page.

It does not show anything when no user logged in.

## d. Possible Cause and/or Solution  
I think something is wrong with "NSurveyReports\****.aspx" codes.
  
## e. Technical Specifications  
- Version of Survey Project:  2.5 (the last test package you sent)
- Type of Device (pc, laptop, tablet, mobile):  all
- Browser Type & Version:  firefox, chrome
- Operating System:  win10, win7
  
## f. Context (Environment)  
There was no problem with "ResultsReport.aspx" on SP2.4.
Maybe something is broken on 2.5

**Comment by w3devpro** [comment]
Issue caused by missing web.config entry setting: authorisation to nsurveyreports directory. Fixed.
