### ISSUE TITLE
Unable to build in localhost

### ISSUE THREAD

**Issue by UlrikMy** [surveyproject/sp_main_public#118]
# 1. ISSUE/ BUG/ ERROR  
## b. Actual Behaviour

After installing the WAP and setting up the database as instructed, I was unable to run the application in localhost. In the debug I get the following error: unable to start program C:\... surveyWAP/bin/Votations.NSurvey.WebAdmin.dll
The system cannot find the .dll extension in the bin. That's one problem. The other problem is when I try to build the application in Visual Studio. I get the following error: 
C:\...\surveyproject-2.4\SurveyWAP\SurveyWAP.csproj(2130,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MSBuildTasks.1.5.0.235\build\MSBuildTasks.targets.

It should be easy enough to install the NuGet package, but I can't do that either. I get the message that the 'Default Project' is not found. See below: 

PM> Install-Package MSBuildTask -Version 1.5.0.235
Install-Package : Project 'Default' is not found.
At line:1 char:16
+ Install-Package <<<<  MSBuildTask -Version 1.5.0.235
    + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

I'd really appreciate some input to help me here. I'm fairly new to this. Thanks, everyone. 
  
## c. Steps to Reproduce Behaviour  

1.  
2.  
3.  
  
## e. Technical Specifications  
- Version of Survey Project:  
- Type of Device (pc, laptop, tablet, mobile):  
- Browser Type & Version:  
- Operating System:  
  
## f. Context (Environment)  

  
____________________________________________________________________  
____________________________________________________________________  
  

# 2. NEW FEATURE  

## b. Acceptance Criteria  

*Scenario 1*  
### Then .....   
*Scenario 2*  
### Then .....   
*Scenario 3*

**Comment by w3devpro** [comment]
Please check the surveyproject.org site for any help and the SP installation documents. Also the Microsoft websites provide information on how to start developing.
