### ISSUE TITLE
Remove binaries from repository

### ISSUE THREAD

**Issue by rubberduck203** [surveyproject/sp_main_public#12]
Add a .gitignore file to the repository so the binaries don't clutter up the diffs and get copied from branch to branch all over the history of the repository. Having them in the repository drastically increases the size of the repo.

Will follow up with a PR.

**Comment by fwsmaster** [comment]
Hello,

Thank you for the advise and the pull request.

Kind regards
SP coordinator

**Comment by ChrisNelsonPE** [comment]
Would also be nice to remove all the cache files that get updated on every build.  I can submit a PR later.

**Comment by rubberduck203** [comment]
:+1: Chris. I know I didn't catch everything in PR #13

**Comment by w3devpro** [comment]
new .gitignore file added (SP 2.4)
