### ISSUE TITLE
Can't import a survey twice

### ISSUE THREAD

**Issue by ChrisNelsonPE** [surveyproject/sp_main_public#24]
I want to revise a survey offline. The workflow I'm considering for this is:
1. Create a survey in my own environment
2. Export the survey
3. Import it to a public place
4. Edit it locally
5. Export it
6. Import the survey as a second survey in the public place
7. Deactivate the old survey
8. Activate the new survey
9. Merge data from the two versions (method TDB)

But at step 6, I get "Another survey with the same name exists in the folder. Please import into different folder."  What folder?  What name?  I gave it a different title.

**Comment by fwsmaster** [comment]
When importing a survey into SP as you noticed there will be a warningmessage if the surveyname (name = title) is already used. 

It's possible however to import the survey with the same name if it's imported into different a (sub)folder of the survey tree list:
- right click (root)folder in treelist, create new folder;
- click/ open new folder, next import survey (to new folder)

As long as there is no survey with the same name in the new folder, there will be no warning.
