### ISSUE TITLE
FileType missing from vts_spFileGetListForGuid

### ISSUE THREAD

**Issue by jonpikum** [surveyproject/sp_main_public#28]
When getting a list of files with the group guid:

`FileData guidFiles = new Answers().GetGuidFiles(this.GroupGuid);`

FileType is always null

The origin of this issue of is that the stored procedure being called (vts_spFileGetListForGuid) does not return FileType.

One specific place FileType is intended to be used but does not behave as intended is in the AnswerUploadItem.cs for displaying the uploaded files.

fix:
change vts_spFileGetListForGuid to be:
`SELECT FileId, GroupGuid, FileName, FileSize, FileType, SaveDate, -1 as VoterId FROM vts_tbFile WHERE GroupGuid = @GroupGuid`

**Comment by fwsmaster** [comment]
Thank you for reporting and the suggested codefix. 

Can you please help answer the following?

You mention the intended use of the FileType field in AnswerUploadItem.cs. If checking the code all the way to its use in the UI screens (e.g. voter report, file manager, or on the survey form) it does not seem to be an issue.

FileType field is never used, except in the filemanager where it shows up correctly (using a different Stored procedure). Adding the FileType field to the Stored procedure will therefore have no visible effects on screen or cause a malfunction of a particular feature.

**Question**: did you find any places where the FileType is actually missing on the UI i.e. should appear but doesnt or cause a malfunction?

Note: the suggested fix will be added for reasons of consistency.

**Comment by jonpikum** [comment]
Now that you mention it, no, I don't see anywhere in the UI that it is being used or displayed... Upon closer inspection, the only time it's referenced is on the download, upload, and delete buttons when setting the LinkButton's CommandArgument...

`button.CommandArgument = string.Format("{0},{1},{2},{3}", new object[] { fileId.ToString(), groupGuid, fileName, fileType });`

I only noticed because I was sifting through the code and debugging and noticed the property was null even though it was being referenced

On a side note, I noticed that `vts_spFileGetDetails` also does not return the FileType

**Comment by w3devpro** [comment]
Corrected in SP v. 2.4
