### ISSUE TITLE
Fileupload files missing on VoterReport in Edit mode

### ISSUE THREAD

**Issue by fwsmaster** [surveyproject/sp_main_public#29]
Current working (SP 2.3.)
1- Create survey including Question with Upload Answer option;
2- submit survey including an uploaded file through the upload question
3- go to reports/ votereports -> click details to open voterreport of submitted  survey
4- the uploaded file is shown correctly on the voterreport screen
5- next switch to Voter Answer Edit mode
6- the (list of) uploaded file(s) no longer shows

Expected situation:
- on step 5/6: the list of uploaded files should be shown (similar to the one shown on the non- editable voter report screen)

**Comment by w3devpro** [comment]
Issue no longer exists in SP 2.4
