### ISSUE TITLE
Procedure or function 'vts_spAnswerAddNew' expects parameter '@CssClass', which was not supplied.

### ISSUE THREAD

**Issue by akdurmus** [surveyproject/sp_main_public#30]
When try to import a xml question I get the error message 
"
Procedure or function 'vts_spAnswerAddNew' expects parameter '@CssClass', which was not supplied.
"

![image](https://cloud.githubusercontent.com/assets/787313/15713839/fd28f4de-280f-11e6-960d-60f62f5f1b73.png)

**Comment by jonpikum** [comment]
Just a note, I think this error only exists in the sp_24_dev branch.

I believe this error also occurs when trying to save a new answer to a question, not just in the import

if you edit 'GetInsertCommand' in Answer.cs inside the SQLServerDAL project to inclue

```
command.Parameters.Add(new SqlParameter("@CssClass", SqlDbType.NVarChar, 50, "CssClass"));
```

and build, you should be good to go on this

**Comment by akdurmus** [comment]
Thanks it seems to solve the problem. But I decided to downgrade to v2.3

**Comment by fwsmaster** [comment]
Just to confirm that the "issue"only concerns SP 2.4 alpha which is not a stable release to be used in production yet. Nevertheless its appreciated the "missing code" is reported. It helps finishing the code for the new CSS features.

**Comment by fwsmaster** [comment]
Code completed in SP 2.4 alpha update 2016/07/01
