### ISSUE TITLE
Answers Default text of default language on Multilanguage survey not shown

### ISSUE THREAD

**Issue by fwsmaster** [surveyproject/sp_main_public#34]
Discovered in SP v. 2.3 (andn in the SP 2.4 alpha version so far)

To replicate:
- create new survey
- set survey to multilanguage (e.g. en-US default + nl-NL second)
- create question + add answer
- set answer default text: [any text} in answereditor for both en-US and nl-NL language
- open weblink to survey, choose default language (en-US)
- the default text does not show
- restart survey: choose second language: the default text does show correcty

Expected situation: 
- default text should show on default language correctly as well

**Comment by w3devpro** [comment]
- Cause: invalid code in the Stored procedures: vts_spQuestionGetAnswers 
- Correction: on isnull the result is now set to defaulttext
- Added to SP 2.4
