### ISSUE TITLE
Custom HTML lost in Question editor

### ISSUE THREAD

**Issue by jameshed** [surveyproject/sp_main_public#4]
I put in this code (so that I can write CSS against the controls)
<input class="toggle-box" id="AdditionalEquipment" type="checkbox">
<label class="toggle-text" for="AdditionalEquipment">My Label</label>

after saving and reloading, it changes to this

<input type="checkbox" /> My label

**Comment by fwsmaster** [comment]
Hi, thanks for reporting. 

SP makes use of the third party component: CKEditor 4.4.3
Certain settings can be adjusted through the files in the scripts/ckeditor files of the SP application.

More information can be found at: http://ckeditor.com

Kind regards,
SP coordinator
