### ISSUE TITLE
scroll form builder by touchpad or touchscreen

### ISSUE THREAD

**Issue by leantalent** [surveyproject/sp_main_public#40]
# NEW FEATURE  

### As a ...  
Survey Creator & SP administrator
### I want to ...   
be able to scroll the SP webpages in a user friendly and unambiguous way on PC's/ laptops and tablets
### So that I can ...   
work efficiently and use different devices to create, publish and administer surveys

### Given...  
the formbuilder webpage (or any other SP webpage)
### When....   
creating a lengthy survey longer than the browsers viewport
### Then .....   
scrolling must be possibe on different devices (PC/ Laptop/ Tablet)

### Given...  
a lenghty SP webpage longer than the browsers viewport
### When....  
its necessary to scroll up and down the page
### Then ..... 
scrolling must be possible by using the cursor or by pointing device   

### Given...  
a lenghty SP webpage longer than the browsers viewport
### When....  
its necessary to scroll up and down the page 
### Then .....  
there can be only one scroll bar necessary to scroll/ view all content

**Comment by w3devpro** [comment]
The SP v.2.4 admin tool is compatible with the use on PC and/ or laptop. It was not designed or tested on tables or other mobile devices. 

The next release v. 2.5 will contain major changes to the admin tool front end (and the survey form as well) to make it (more) compatible with tablets as well (e.g. table structures replaced by DIV, scrolling within fixed frame, current scrollbar replaced). 

Main purpose it to be able to create fully "responsive" survey forms for both pc/laptop and mobile devices.
