### ISSUE TITLE
Question and Basic AnswerText Box on Same Line

### ISSUE THREAD

**Issue by rcmsoftwaredevelopment** [surveyproject/sp_main_public#49]
Hi People

Is there anyway through css or code where I can align the Question and Answer on the same line such 

Question    Answer

Rather than 

Question
Answer

For example this would be requried when asking for name , etc.

Thanks

Ray

**Comment by w3devpro** [comment]
Hi Ray,
 
You may have missed the following:

### Issues, Questions, Requests

Technical Issues (e.g. bugs, errors or feature requests) concerning the use and development of SP can be registered on the Github site.

**Useability "Issues" i.e. questions on the use, installation or development of the SP webapplication or surveys can be posted to the Community site Forums.**

On opening a new Issue on Github a template will show that can only be used for:
a. bugs/ errors
b. new features requests

You can find the Sp forums and answer to your question at:
[SP Forum and Answer](http://www.surveyproject.org/Forums/tabid/107/forumid/6/threadid/502/scope/posts/Default.aspx)

This item will be closed.
