### ISSUE TITLE
Multiple Survey submission problem: refresh page or browse back

### ISSUE THREAD

**Issue by worldstar** [surveyproject/sp_main_public#50]
# 1. ISSUE/ BUG/ ERROR  
## a. Expected Behaviour
To block a person to submit the same questionnaire many times.
  
## b. Actual Behaviour
When they submit the questionnaire, they could click "Back" button of the browser. Then, they could submit the same questionnaire again and we see the database received the 2nd record. In addition, on the page of the questionnaire, when a user clicks the "Submit" button twice, there are two questionnaire records.
  
## c. Steps to Reproduce Behaviour  
1.  Submit a questionnaire and the system shows a thank you information.
2.  Click the button "Back" on the browser.
3.  Submit this questionnaire again.
  
The other problem is:
1.  Click the button "Submit" quickly twice.

## d. Possible Cause and/or Solution  
We get the information from the forum. 
http://www.surveyproject.org/Forums/tabid/107/forumid/6/threadid/514/scope/posts/Default.aspx
However, it is not the solution we expect.
  
## e. Technical Specifications  
- Version of Survey Project:  2.3
- Type of Device (pc, laptop, tablet, mobile):  PC
- Browser Type & Version:  Chrome
- Operating System:  Windows 7, Mac OSX

**Comment by w3devpro** [comment]
Perfect use of the issue form, thanks for submitting.

**Comment by worldstar** [comment]
Thank you.

**Comment by w3devpro** [comment]
**Analysis**
- as described two different scenarios cause the issue of "multiple/ repeated submissions" that each requires a separate 'solution'
_* scenario 1._ Fast or double clicking the submit button of the survey will cause multiple entries;
_* scenario 2._ After a regular submit ->
a.  a browser refresh (F5) of the page or
b. clicking the go back browser button and re click the submit button ->
will both cause double/ multiple entries.

**Solutions**
_*scenario 1. :_   an onclick event is added to the submit button through the (Surveybox.cs) code behind of the aspx page which will disable the button after a 0 sec. timedelay which is needed to get the form submitted at all; 

_*scenario 2.:_  
- technically it is (almost) impossible to prevent the user from browsing back or refreshing the page (which will automatically repeat the submit action) 
- there may also be user scenarios where is it required to be able to resubmit the same results multiple times (eg webform/ dataentry situations) in which case blocking refresh may be unwanted;
- a working solution that makes use of the already existing SP Security add ins is advised:
*  if the Cookie security add in is added to the survey including a brief timeout (min. option: 1 min.) both a page back resubmit or a page refresh will not cause double entries. 
- there will however be no warning /message to inform the user. This will only be shown if the survey is restarted while the cookie has not yet expired.

**Comment by worldstar** [comment]
Dear Survey team,
   Thank you for your instructions.
We could try to update the "Surveybox.cs" first for the 1st scenario.
So we shall report the results back to you soon.
Many thanks for your quick assistance again.

Best Regards,
Shih-Hsin

------------------------------------------------------------------
Shih-Hsin Chen <http://peterchenweb.appspot.com/>, Ph.D.
Associate Professor,
Department of Information Management,
Group Lead of the System Development,
Cheng Shiu University, Taiwan, R. O. C.
Phone: +886-7-735-8800 ext. 5307
------------------------------------------------------------------

2018-01-21 1:00 GMT+08:00 W3DevPro <notifications@github.com>:

**Comment by w3devpro** [comment]
Hello Shih-Hsin,

If you want to make the change yourself (it will be part of SP v. 2.5) the following is needed:
- project WebControls
- directory WebControls
- file surveybox.cs
- method protected virtual Panel BuildSubmitButtonRow()

Added code:
`this._submitButton.OnClientClick = "var e=this;setTimeout(function(){e.disabled=true;},0);return true;";`

Note: the time out is needed to still be able to submit the answers before the button is disabled. Timout can be set to 0.

Kind regards,
SP

**Comment by worldstar** [comment]
Dear SP,
   Thank you for your quick response
because you further instruct what are the places we should take care of the
Version 2.5.
Wish there is no problem when my colleague upgrades the questionnaire
system.

Sincerely,
Shih-Hsin

------------------------------------------------------------------
Shih-Hsin Chen <http://peterchenweb.appspot.com/>, Ph.D.
Associate Professor,
Department of Information Management,
Group Lead of the System Development,
Cheng Shiu University, Taiwan, R. O. C.
Phone: +886-7-735-8800 ext. 5307
------------------------------------------------------------------

2018-01-21 18:49 GMT+08:00 W3DevPro <notifications@github.com>:
