### ISSUE TITLE
FeatReq: Confirmation on bulk user uploads

### ISSUE THREAD

**Issue by jonpikum** [surveyproject/sp_main_public#6]
Background:
I had used a script to format most of my user data and didn't look at it super close (~100 users)
I opted to use the user's email address as their username for logging in.
Two of our users shared the same email, and therefore shared the same username.
The second of these users was not created, but no error message was given, the only way I knew any had failed was that I went to double check the number of rows added in the database.

Request:
Just as a simple feature, it would be nice to see "Of X attempted user uploads, Y were successful" or even just "X of Y successful" since the context of the user's action is fairly obvious.
I understand that wanting a bunch of feedback on a bulk upload can be a little silly, but totals would probably help a lot.  I managed to find the missing user pretty quickly, but I thought this might be quick to implement and could help someone else in the future

**Comment by w3devpro** [comment]
Added solution:. Import users  - new warning information messages: - DONE
- nr of lines submitted
- nr of users imported
- Import halted on error + info
* invalid password
* invalid delimiter format
* user already exists

* on succesfull import: nr of imported + nr. of lines submitted
