### ISSUE TITLE
Graphical Reports appear to do nothing

### ISSUE THREAD

**Issue by rubberduck203** [surveyproject/sp_main_public#7]
I don't know what else I can say or provide here. Select a survey, go to Results >> Reports. Click on... _everything_ but Graphical Reports do nothing at all. The other two options seem to work.

**Comment by rubberduck203** [comment]
I've actually narrowed this down a little bit. In `ResultsReporting.aspx.cs` there's this bit of code.

```
    protected void rbListSelectedIndexChanged(object sender, EventArgs e)
    {
        switch (rblReports.SelectedValue)
        {
            case "GR": Response.Redirect(UINavigator.ResultsReportHyperlink); break;
```

Checking on the definition of `UINavigator.ResultsReportHyperlink` shows that the "Graphical Report" selection points back to `ResultsReporting.aspx`. So, I'm not sure what this is actually _supposed_ to do, but right now it just redirects back to the same page.

**Comment by fwsmaster** [comment]
Hello,

After selecting survey, go to results >> reports >> Graphical reports selected by default 
--> next have you tried selecting an option from the Dropdownlist "Question Results to display"?
That should bring up the results.

Note v.2.4 will contain some major updates to the Reporting options. Check the development branch.

Kind regards
SP Coordinator

**Comment by rubberduck203** [comment]
So this is fixed in the development branch? Would you mind pointing me to the commit or file?
