### ISSUE TITLE
Scrolling and page frame

### ISSUE THREAD

**Issue by marksburgess** [surveyproject/sp_main_public#9]
The forms sometimes do not expose action buttons and don't allow scrolling within the page.  Recommend removing fixed footer and stop truncating display.

**Comment by fwsmaster** [comment]
Can you please add a more detailed description: when and where, which forms/page, what browser are you using?

**Comment by marksburgess** [comment]
I tried it in Chrome, Firefox, Safari and Windows 10 Explorer, VIsta Explorer and Vista Chrome.  Any form longer than the screen is frozen in place for the prescribed height of the screen.  The one place it works is on a local machine.  Could it be a publishing path issue on the server?

**Comment by fwsmaster** [comment]
you may have to check the perfect scroll bar css and javascript and see if it's properly loaded/ working on your server; the issue has not been reported before and cannot be replicated on our servers;

**Comment by marksburgess** [comment]
It appears that when the project inside the Visual Studio solution did not have the jquery-ui-1.10.4.js file.  Once I published that file to the server, everything worked.  For some reason, most of the files in UI folder did not get loaded into the solution on one of my development machines.  They all loaded on the first machine.
