### ISSUE TITLE
Wrong score calculation on resultsrepost.aspx page

### ISSUE THREAD

**Issue by trup40** [surveyproject/sp_main_public#96]
# 1. ISSUE/ BUG/ ERROR  
## a. Expected Behaviour
There must be the correct calculation on resultsreport.aspx page.
For example;
score from q1: 2
score from q2: 3
score from q3: 4
total score: 9

Total score for this example must be 9 on resultsreport.aspx page.
  
## b. Actual Behaviour
It shows 18 (2*9) on resultsreport.aspx page.
  
## c. Steps to Reproduce Behaviour  

1.  Sum all the scores in new way
  
## d. Possible Cause and/or Solution  
1.  Get correct scores via C# code like this "<%=Convert.ToInt32(Session["voterid"]) %>"
2.  An additional code for dividing wrong score by 2.
  
## e. Technical Specifications  
- Version of Survey Project:  2.4
- Type of Device (pc, laptop, tablet, mobile):  All
- Browser Type & Version:  Firefox, Chrome, Internet Explorer
- Operating System:  Win10, Win7, Android Nougat
  
## f. Context (Environment)  

This is very important to get satisfied usage of SP.
SP must show the correct number (it is its style :))

**Comment by w3devpro** [comment]
Issue added to SP 2.5 development project. Cause found in resultsreport.aspx cs codebehind and fixed.

**Comment by w3devpro** [comment]
see #98 also
